# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a7c304129102a79544d8ddec0a700ff51acaf28ec5ac92e69afe02466d5e8957cb87bbbe3ad8f32790637477639d756f34c17a5796f276229d20b82fcb911b

test:
  secret_key_base: a0450c9cc4198d09385e60666925cea1ebb44b12db6c92e8b91deaf49f141955129e5239e10f18b61199fa86157c108e87bf57cebd9b9ea113d1c34d36824f8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
